services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/temperatureDB
      - PORT=5000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=strongpassword
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/
      - TZ=Asia/Kolkata
      - EXECUTIONS_PROCESS=main
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  mongo-data: {}
  n8n_data: {}
